"use client";
import { FormEvent, useState } from "react";
import Swal from "sweetalert2";
import { newHistoricalDraft,salnAdminApi,type HistoricalDraft,type OwnerType,type SourceType } from "@/lib/services/saln";
import styles from "./SalnAdministration.module.scss";

interface EmployeeOption{employeeId:number;employeeNo?:string;fullName?:string;firstname?:string;lastname?:string;suffix?:string;}
const employeeLabel=(employee:EmployeeOption)=>`${employee.employeeNo||"No employee no."} — ${employee.fullName||[employee.firstname,employee.lastname,employee.suffix].filter(Boolean).join(" ")}`;
const replace=<T,>(rows:T[],index:number,row:T)=>rows.map((item,i)=>i===index?row:item);
const owner={ownerType:"DECLARANT" as OwnerType,ownerName:""};
const message=(error:unknown)=>error instanceof Error?error.message:"Historical SALN could not be encoded.";

export default function HistoricalSalnForm({employees,onCreated}:{employees:EmployeeOption[];onCreated:()=>Promise<void>}){
 const [employeeId,setEmployeeId]=useState("");const [employeeQuery,setEmployeeQuery]=useState("");const [sourceType,setSourceType]=useState<SourceType>("PAPER");const [originalFilingDate,setOriginalFilingDate]=useState("");const [reference,setReference]=useState("");const [draft,setDraft]=useState<HistoricalDraft>(newHistoricalDraft());const [saving,setSaving]=useState(false);
 const set=<K extends keyof HistoricalDraft>(key:K,value:HistoricalDraft[K])=>setDraft(current=>({...current,[key]:value}));
 const submit=async(event:FormEvent)=>{event.preventDefault();if(!employeeId){await Swal.fire("Select a valid employee","Choose an employee from the autocomplete suggestions before encoding the historical SALN.","warning");return;}const confirmation=await Swal.fire({title:"Encode historical SALN?",text:"This creates an immutable compliant version from the identified source document. Confirm that the data was transcribed faithfully.",icon:"warning",showCancelButton:true,confirmButtonText:"Encode historical record"});if(!confirmation.isConfirmed)return;setSaving(true);try{await salnAdminApi.historical({employeeId:Number(employeeId),sourceType,originalFilingDate,sourceDocumentReference:reference,declaration:draft});setDraft(newHistoricalDraft());setEmployeeId("");setEmployeeQuery("");setOriginalFilingDate("");setReference("");await onCreated();await Swal.fire("Historical SALN encoded","The source, original filing date, version, and audit event were recorded.","success");}catch(error){await Swal.fire("Unable to encode SALN",message(error),"error");}finally{setSaving(false);}};
 return <section className={styles.historical}><h2>Historical SALN encoding</h2><p>Transcribe a signed paper or legacy filing. The employee remains the declarant; the HR encoder and source document are recorded separately.</p>
  <form onSubmit={submit} className={styles.historicalForm}>
   <fieldset disabled={saving}><legend>Source and filing</legend><div className={styles.formGrid}>
    <label>Employee<input required type="search" list="historical-saln-employees" autoComplete="off" value={employeeQuery} placeholder="Search employee no. or name" onChange={e=>{const value=e.target.value;setEmployeeQuery(value);const selected=employees.find(employee=>employeeLabel(employee)===value);setEmployeeId(selected?String(selected.employeeId):"");}}/><datalist id="historical-saln-employees">{employees.map(employee=><option key={employee.employeeId} value={employeeLabel(employee)}/>)}</datalist><small>{employeeId?"Employee selected.":"Select an exact suggestion to continue."}</small></label>
    <label>Source<select value={sourceType} onChange={e=>setSourceType(e.target.value as SourceType)}><option value="PAPER">Signed paper filing</option><option value="LEGACY_MIGRATION">Legacy system migration</option><option value="ADMIN_ENCODED">Administrative encoding</option></select></label>
    <label>Original filing date<input required type="date" value={originalFilingDate} onChange={e=>setOriginalFilingDate(e.target.value)}/></label><label>Source document reference<input required value={reference} onChange={e=>setReference(e.target.value)} placeholder="Box/folder/scanned-document reference"/></label>
    <label>Filing type<select value={draft.filingType} onChange={e=>set("filingType",e.target.value as HistoricalDraft["filingType"])}><option>ANNUAL</option><option>ASSUMPTION</option><option>SEPARATION</option></select></label><label>SALN year<input required type="number" min="1900" max="2200" value={draft.salnYear} onChange={e=>set("salnYear",Number(e.target.value))}/></label><label>Reference / as-of date<input required type="date" value={draft.referenceDate} onChange={e=>set("referenceDate",e.target.value)}/></label><label>Filing arrangement<select value={draft.filingMode} onChange={e=>set("filingMode",e.target.value as HistoricalDraft["filingMode"])}><option value="JOINT">Joint</option><option value="SEPARATE">Separate</option><option value="NOT_APPLICABLE">Not applicable</option></select></label>
   </div></fieldset>
   <fieldset disabled={saving}><legend>Declarant and spouse information</legend><div className={styles.formGrid}>{([['declarantMiddleInitial','Middle initial'],['declarantPosition','Position'],['declarantAgencyOffice','Agency / office'],['declarantOfficeAddress','Office address'],['spouseFullName','Spouse full name'],['spousePosition','Spouse position'],['spouseAgencyOffice','Spouse agency / office'],['spouseOfficeAddress','Spouse office address'],['multipleSpouses','Other spouse names, if applicable']] as const).map(([key,label])=><label key={key}>{label}<input value={draft[key]} onChange={e=>set(key,e.target.value)}/></label>)}</div></fieldset>
   <fieldset disabled={saving}><legend>Children below 18</legend>{draft.dependents.map((row,i)=><div className={styles.dataRow} key={i}><input required placeholder="Name" value={row.name} onChange={e=>set("dependents",replace(draft.dependents,i,{...row,name:e.target.value}))}/><input required placeholder="Relationship" value={row.relationship} onChange={e=>set("dependents",replace(draft.dependents,i,{...row,relationship:e.target.value}))}/><input required type="number" min="0" max="17" placeholder="Age" value={row.age} onChange={e=>set("dependents",replace(draft.dependents,i,{...row,age:Number(e.target.value)}))}/><Remove onClick={()=>set("dependents",draft.dependents.filter((_,x)=>x!==i))}/></div>)}<Add label="Add child" onClick={()=>set("dependents",[...draft.dependents,{name:"",relationship:"CHILD",age:0}])}/></fieldset>
   <fieldset disabled={saving}><legend>Real properties</legend>{draft.realProperties.map((row,i)=><div className={styles.dataRow} key={i}><Owner value={row.ownerType} name={row.ownerName||""} onChange={(ownerType,ownerName)=>set("realProperties",replace(draft.realProperties,i,{...row,ownerType,ownerName}))}/>{([['description','Description'],['kind','Kind'],['exactLocation','Exact location'],['assessedValue','Assessed value'],['fairMarketValue','Fair market value'],['acquisitionYear','Acquisition year'],['acquisitionMode','Acquisition mode'],['acquisitionCost','Acquisition cost']] as const).map(([key,label])=><input key={key} required value={row[key]} type={key.includes('Value')||key.includes('Cost')||key==='acquisitionYear'?"number":"text"} min={key==='acquisitionYear'?1000:0} step={key==='acquisitionYear'?1:"0.01"} placeholder={label} onChange={e=>set("realProperties",replace(draft.realProperties,i,{...row,[key]:key==='acquisitionYear'?Number(e.target.value):e.target.value}))}/>) }<Remove onClick={()=>set("realProperties",draft.realProperties.filter((_,x)=>x!==i))}/></div>)}<Add label="Add real property" onClick={()=>set("realProperties",[...draft.realProperties,{...owner,description:"",kind:"",exactLocation:"",assessedValue:"",fairMarketValue:"",acquisitionYear:draft.salnYear,acquisitionMode:"",acquisitionCost:""}])}/></fieldset>
   <fieldset disabled={saving}><legend>Personal properties</legend>{draft.personalProperties.map((row,i)=><div className={styles.dataRow} key={i}><Owner value={row.ownerType} name={row.ownerName||""} onChange={(ownerType,ownerName)=>set("personalProperties",replace(draft.personalProperties,i,{...row,ownerType,ownerName}))}/><input required placeholder="Description" value={row.description} onChange={e=>set("personalProperties",replace(draft.personalProperties,i,{...row,description:e.target.value}))}/><input required type="number" min="1000" placeholder="Acquisition year" value={row.acquisitionYear} onChange={e=>set("personalProperties",replace(draft.personalProperties,i,{...row,acquisitionYear:Number(e.target.value)}))}/><input required type="number" min="0" step="0.01" placeholder="Acquisition cost" value={row.acquisitionCost} onChange={e=>set("personalProperties",replace(draft.personalProperties,i,{...row,acquisitionCost:e.target.value}))}/><Remove onClick={()=>set("personalProperties",draft.personalProperties.filter((_,x)=>x!==i))}/></div>)}<Add label="Add personal property" onClick={()=>set("personalProperties",[...draft.personalProperties,{...owner,description:"",acquisitionYear:draft.salnYear,acquisitionCost:""}])}/></fieldset>
   <fieldset disabled={saving}><legend>Liabilities</legend>{draft.liabilities.map((row,i)=><div className={styles.dataRow} key={i}><Owner value={row.ownerType} name={row.ownerName||""} onChange={(ownerType,ownerName)=>set("liabilities",replace(draft.liabilities,i,{...row,ownerType,ownerName}))}/><input required placeholder="Nature" value={row.nature} onChange={e=>set("liabilities",replace(draft.liabilities,i,{...row,nature:e.target.value}))}/><input required placeholder="Creditor" value={row.creditorName} onChange={e=>set("liabilities",replace(draft.liabilities,i,{...row,creditorName:e.target.value}))}/><input required type="number" min="0" step="0.01" placeholder="Outstanding balance" value={row.outstandingBalance} onChange={e=>set("liabilities",replace(draft.liabilities,i,{...row,outstandingBalance:e.target.value}))}/><Remove onClick={()=>set("liabilities",draft.liabilities.filter((_,x)=>x!==i))}/></div>)}<Add label="Add liability" onClick={()=>set("liabilities",[...draft.liabilities,{...owner,nature:"",creditorName:"",outstandingBalance:""}])}/></fieldset>
   <fieldset disabled={saving}><legend>Business interests</legend><label><input type="checkbox" checked={draft.businessInterestsNone} onChange={e=>{set("businessInterestsNone",e.target.checked);if(e.target.checked)set("businessInterests",[]);}}/> None declared in source</label>{draft.businessInterests.map((row,i)=><div className={styles.dataRow} key={i}><Owner value={row.ownerType} name={row.ownerName||""} onChange={(ownerType,ownerName)=>set("businessInterests",replace(draft.businessInterests,i,{...row,ownerType,ownerName}))}/><input required placeholder="Entity" value={row.entityName} onChange={e=>set("businessInterests",replace(draft.businessInterests,i,{...row,entityName:e.target.value}))}/><input required placeholder="Address" value={row.businessAddress} onChange={e=>set("businessInterests",replace(draft.businessInterests,i,{...row,businessAddress:e.target.value}))}/><input required placeholder="Nature" value={row.nature} onChange={e=>set("businessInterests",replace(draft.businessInterests,i,{...row,nature:e.target.value}))}/><input type="date" value={row.dateAcquired} onChange={e=>set("businessInterests",replace(draft.businessInterests,i,{...row,dateAcquired:e.target.value}))}/><Remove onClick={()=>set("businessInterests",draft.businessInterests.filter((_,x)=>x!==i))}/></div>)}{!draft.businessInterestsNone&&<Add label="Add business interest" onClick={()=>set("businessInterests",[...draft.businessInterests,{...owner,entityName:"",businessAddress:"",nature:"",dateAcquired:""}])}/>}</fieldset>
   <fieldset disabled={saving}><legend>Relatives in government</legend><label><input type="checkbox" checked={draft.relativesInGovernmentNone} onChange={e=>{set("relativesInGovernmentNone",e.target.checked);if(e.target.checked)set("governmentRelatives",[]);}}/> None declared in source</label>{draft.governmentRelatives.map((row,i)=><div className={styles.dataRow} key={i}>{(['name','relationship','position','agencyOfficeAddress'] as const).map(key=><input key={key} required placeholder={key.replaceAll(/([A-Z])/g," $1")} value={row[key]} onChange={e=>set("governmentRelatives",replace(draft.governmentRelatives,i,{...row,[key]:e.target.value}))}/>)}<Remove onClick={()=>set("governmentRelatives",draft.governmentRelatives.filter((_,x)=>x!==i))}/></div>)}{!draft.relativesInGovernmentNone&&<Add label="Add relative" onClick={()=>set("governmentRelatives",[...draft.governmentRelatives,{name:"",relationship:"",position:"",agencyOfficeAddress:""}])}/>}</fieldset>
   <fieldset disabled={saving}><legend>Identification and source certification</legend><div className={styles.formGrid}><label>Government ID type<input required value={draft.governmentIdType} onChange={e=>set("governmentIdType",e.target.value)}/></label><label>ID number<input required value={draft.governmentIdNo} onChange={e=>set("governmentIdNo",e.target.value)}/></label><label>Date issued<input required type="date" value={draft.governmentIdDateIssued} onChange={e=>set("governmentIdDateIssued",e.target.value)}/></label><label>Encoding remarks<textarea value={draft.remarks} onChange={e=>set("remarks",e.target.value)}/></label></div><label><input required type="checkbox" checked={draft.certificationAccepted} onChange={e=>set("certificationAccepted",e.target.checked)}/> The identified source document contains the declarant&apos;s signed certification, and this encoding faithfully reflects it.</label></fieldset>
   <button className={styles.primaryAction} disabled={saving} type="submit">{saving?"Encoding...":"Encode immutable historical SALN"}</button>
  </form>
 </section>;
}
function Owner({value,name,onChange}:{value:OwnerType;name:string;onChange:(type:OwnerType,name:string)=>void}){return <><select aria-label="Owner" value={value} onChange={e=>onChange(e.target.value as OwnerType,name)}><option>DECLARANT</option><option>SPOUSE</option><option>CHILD</option></select>{value!=="DECLARANT"&&<input required aria-label="Owner name" placeholder="Owner name" value={name} onChange={e=>onChange(value,e.target.value)}/>}</>}
function Add({label,onClick}:{label:string;onClick:()=>void}){return <button type="button" onClick={onClick}>{label}</button>}
function Remove({onClick}:{onClick:()=>void}){return <button type="button" onClick={onClick}>Remove</button>}
