"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import Swal from "sweetalert2";
import { fetchWithAuth } from "@/lib/utils/fetchWithAuth";
import { localStorageUtil } from "@/lib/utils/localStorageUtil";
import { runtimeConfig } from "@/lib/utils/runtimeConfig";
import { salnAdminApi,type Audit,type Dashboard,type FilingType,type RecordDetail,type Requirement,type SalnStatus,type Summary } from "@/lib/services/saln";
import modalStyles from "@/styles/Modal.module.scss";
import styles from "./SalnAdministration.module.scss";
import HistoricalSalnForm from "./HistoricalSalnForm";

interface EmployeeBasicInfo{employeeId:number;employeeNo?:string;fullName?:string;firstname?:string;lastname?:string;suffix?:string;}
const initialDashboard:Dashboard={totalRequired:0,filed:0,notFiled:0,draft:0,submitted:0,underReview:0,forCorrection:0,compliant:0,overdue:0};
const REQUIREMENTS_PER_PAGE=12;
const peso=(value:number|string)=>Number(value).toLocaleString("en-PH",{style:"currency",currency:"PHP"});
const errorText=(error:unknown)=>error instanceof Error?error.message:"The SALN operation could not be completed.";
const previewPdf=async(id:number)=>{try{const blob=await salnAdminApi.pdf(id);const url=URL.createObjectURL(blob);window.open(url,"_blank","noopener,noreferrer");window.setTimeout(()=>URL.revokeObjectURL(url),60_000);}catch(error){await Swal.fire("Unable to generate PDF",errorText(error),"error");}};

export default function SalnAdministration(){
 const reviewPermission=localStorageUtil.getFeaturePermission("hrm.saln.review");const auditPermission=localStorageUtil.getFeaturePermission("hrm.saln.audit");const requirementPermission=localStorageUtil.getFeaturePermission("hrm.saln.requirements");const historicalPermission=localStorageUtil.getFeaturePermission("hrm.saln.historical");
 const [records,setRecords]=useState<Summary[]>([]);const [dashboard,setDashboard]=useState(initialDashboard);const [detail,setDetail]=useState<RecordDetail|null>(null);const [audits,setAudits]=useState<Audit[]>([]);const [requirements,setRequirements]=useState<Requirement[]>([]);const [employees,setEmployees]=useState<EmployeeBasicInfo[]>([]);
 const [year,setYear]=useState("");const [filingType,setFilingType]=useState("");const [status,setStatus]=useState("");const [employeeSearch,setEmployeeSearch]=useState("");const [busy,setBusy]=useState(false);
 const [correction,setCorrection]=useState({section:"",field:"",message:""});const [repository,setRepository]=useState({repositoryAgency:"",submittedAt:"",referenceNo:"",remarks:""});const [requirement,setRequirement]=useState({employeeId:"",filingType:"ANNUAL" as FilingType,referenceDate:`${new Date().getFullYear()}-12-31`});const [bulkYear,setBulkYear]=useState(new Date().getFullYear());const [requirementStatus,setRequirementStatus]=useState("ALL");const [requirementPage,setRequirementPage]=useState(1);
 const query=useMemo(()=>{const q=new URLSearchParams();if(year)q.set("year",year);if(filingType)q.set("filingType",filingType);if(status)q.set("status",status);if(employeeSearch)q.set("employee",employeeSearch);return q;},[year,filingType,status,employeeSearch]);
 const filteredRequirements=useMemo(()=>requirementStatus==="ALL"?requirements:requirements.filter(item=>item.status===requirementStatus),[requirements,requirementStatus]);const requirementPageCount=Math.max(1,Math.ceil(filteredRequirements.length/REQUIREMENTS_PER_PAGE));const safeRequirementPage=Math.min(requirementPage,requirementPageCount);const visibleRequirements=filteredRequirements.slice((safeRequirementPage-1)*REQUIREMENTS_PER_PAGE,safeRequirementPage*REQUIREMENTS_PER_PAGE);
 const refresh=useCallback(async()=>{setBusy(true);try{const [list,metrics]=await Promise.all([salnAdminApi.list(query),salnAdminApi.dashboard(query)]);setRecords(list);setDashboard(metrics);if(requirementPermission.canAccess)setRequirements(await salnAdminApi.requirements());}catch(error){await Swal.fire("Unable to load SALN administration",errorText(error),"error");}finally{setBusy(false);}},[query,requirementPermission.canAccess]);
 useEffect(()=>{void refresh();},[refresh]);
 useEffect(()=>{if(!requirementPermission.canAdd&&!historicalPermission.canAdd)return;void fetchWithAuth(`${runtimeConfig.getApiUrl("hrm")}/api/employees/basicInfo`).then(async response=>{if(response.ok)setEmployees(await response.json() as EmployeeBasicInfo[]);});},[requirementPermission.canAdd,historicalPermission.canAdd]);
 const open=async(id:number)=>{setBusy(true);try{setDetail(await salnAdminApi.get(id));setAudits(auditPermission.canAccess?await salnAdminApi.audit(id):[]);}catch(error){await Swal.fire("Unable to open SALN",errorText(error),"error");}finally{setBusy(false);}};
 const perform=async(action:()=>Promise<RecordDetail>,success:string)=>{setBusy(true);try{const updated=await action();setDetail(updated);await refresh();if(auditPermission.canAccess)setAudits(await salnAdminApi.audit(updated.id));await Swal.fire("Completed",success,"success");}catch(error){await Swal.fire("Action failed",errorText(error),"error");}finally{setBusy(false);}};
 const createRequirement=async()=>{
  if(!requirement.employeeId){
   await Swal.fire("Select an employee","Choose the employee who needs the filing requirement, then try again.","warning");
   return;
  }
  if(!requirement.referenceDate){
   await Swal.fire("Select a reference date","A reference date is required to create the filing requirement.","warning");
   return;
  }
  setBusy(true);try{await salnAdminApi.createRequirement(Number(requirement.employeeId),requirement.filingType,requirement.referenceDate);await refresh();await Swal.fire("Requirement created","The employee filing requirement is now monitored.","success");}catch(error){await Swal.fire("Unable to create requirement",errorText(error),"error");}finally{setBusy(false);}
 };
 const generateAnnualRequirements=async()=>{setBusy(true);try{const preview=await salnAdminApi.annualRequirementPreview(bulkYear);const confirmation=await Swal.fire({title:`Generate annual ${bulkYear} requirements?`,html:`<p><strong>${preview.requirementsCreated}</strong> requirements will be created.</p><p>${preview.alreadyExisting} already exist and will be skipped; ${preview.excludedEmployees} employees are excluded because they are not eligible as of ${preview.referenceDate}.</p><p>Due date: <strong>${preview.dueDate}</strong></p>`,icon:"question",showCancelButton:true,confirmButtonText:"Generate requirements"});if(!confirmation.isConfirmed)return;const result=await salnAdminApi.generateAnnualRequirements(bulkYear);await refresh();await Swal.fire("Annual requirements generated",`${result.requirementsCreated} created, ${result.alreadyExisting} already existed, and ${result.excludedEmployees} were excluded.`,"success");}catch(error){await Swal.fire("Unable to generate requirements",errorText(error),"error");}finally{setBusy(false);}};
 return <div className={modalStyles.Modal}>
  <div className={modalStyles.modalContent}>
   <div className={modalStyles.modalHeader}>
    <h2 className={modalStyles.mainTitle}>SALN Administration</h2>
   </div>
   <div className={modalStyles.modalBody}>
    <div className={styles.page}>
  <button type="button" onClick={()=>void salnAdminApi.compliance(query).then(blob=>{const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download="SALN_Compliance.csv";anchor.click();URL.revokeObjectURL(url);}).catch(async error=>Swal.fire("Unable to export report",errorText(error),"error"))}>Export compliance CSV</button>
  <header><div><p>SALN administration</p><h1>Review and compliance workspace</h1><span>Completeness review only — declaration contents remain employee-owned.</span></div></header>
  <section className={styles.metrics}>{Object.entries(dashboard).map(([key,value])=><article key={key}><span>{key.replace(/([A-Z])/g," $1")}</span><strong>{value}</strong></article>)}</section>
  {historicalPermission.canAdd&&<HistoricalSalnForm employees={employees} onCreated={refresh}/>} 
  <section className={styles.filters}><label>Year<input type="number" value={year} onChange={e=>setYear(e.target.value)}/></label><label>Filing type<select value={filingType} onChange={e=>setFilingType(e.target.value)}><option value="">All</option><option>ANNUAL</option><option>ASSUMPTION</option><option>SEPARATION</option></select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All</option>{(["DRAFT","SUBMITTED","UNDER_REVIEW","FOR_CORRECTION","RESUBMITTED","COMPLIANT","LOCKED","VOIDED"] as SalnStatus[]).map(value=><option key={value}>{value}</option>)}</select></label><label>Employee<input value={employeeSearch} onChange={e=>setEmployeeSearch(e.target.value)} placeholder="Name or employee no."/></label></section>
  <section className={styles.tableCard}><h2>Employee SALNs</h2><div className={styles.tableWrap}><table><thead><tr><th>Employee</th><th>Filing</th><th>Due</th><th>Submitted</th><th>Status</th><th>Net worth</th><th></th></tr></thead><tbody>{records.map(row=><tr key={row.id}><td><strong>{row.employeeName}</strong><small>{row.employeeNo}</small></td><td>{row.filingType} {row.salnYear}<small>Version {row.versionNo}</small></td><td>{row.dueDate}</td><td>{row.submissionDate||"—"}</td><td><span className={styles.status}>{row.status.replaceAll("_"," ")}</span></td><td>{peso(row.netWorth)}</td><td><button type="button" onClick={()=>void open(row.id)}>Review</button></td></tr>)}</tbody></table>{!busy&&records.length===0&&<p>No records match the filters.</p>}</div></section>
   {detail&&<section className={styles.review}><div className={styles.reviewHeader}><div><p>{detail.employeeNo}</p><h2>{detail.employeeName}</h2><span>{detail.filingType} {detail.salnYear} • {detail.status.replaceAll("_"," ")} • Version {detail.versionNo}</span></div><div className={styles.detailHeaderActions}><button type="button" onClick={()=>void previewPdf(detail.id)}>Preview / print CSC SALN PDF</button><button type="button" onClick={()=>setDetail(null)}>Close</button></div></div><div className={styles.summary}><article><span>Total assets</span><strong>{peso(detail.totals.totalAssets)}</strong></article><article><span>Total liabilities</span><strong>{peso(detail.totals.totalLiabilities)}</strong></article><article><span>Net worth</span><strong>{peso(detail.totals.netWorth)}</strong></article></div>
   <div className={styles.sections}><article><h3>Declarant</h3><p>{detail.declarantFamilyName}, {detail.declarantFirstName}</p><p>{detail.declarantPosition||"—"}</p><p>{detail.declarantAgencyOffice||"—"}</p><p>{detail.declarantOfficeAddress||"—"}</p></article><article><h3>Real properties ({detail.realProperties.length})</h3>{detail.realProperties.map((item,index)=><p key={index}>{item.description} — {item.kind}, {item.exactLocation} — {peso(item.acquisitionCost)}</p>)}</article><article><h3>Personal properties ({detail.personalProperties.length})</h3>{detail.personalProperties.map((item,index)=><p key={index}>{item.description} — {peso(item.acquisitionCost)}</p>)}</article><article><h3>Liabilities ({detail.liabilities.length})</h3>{detail.liabilities.map((item,index)=><p key={index}>{item.nature}, {item.creditorName} — {peso(item.outstandingBalance)}</p>)}</article><article><h3>Business interests</h3>{detail.businessInterestsNone?<p>Declared none.</p>:detail.businessInterests.map((item,index)=><p key={index}>{item.entityName} — {item.nature}</p>)}</article><article><h3>Relatives in government</h3>{detail.relativesInGovernmentNone?<p>Declared none known.</p>:detail.governmentRelatives.map((item,index)=><p key={index}>{item.name} — {item.relationship}, {item.position}, {item.agencyOfficeAddress}</p>)}</article></div>
   <div className={styles.actions}>{(detail.status==="SUBMITTED"||detail.status==="RESUBMITTED")&&reviewPermission.canEdit&&<button onClick={()=>void perform(()=>salnAdminApi.start(detail.id),"Review started.")}>Start review</button>}{detail.status==="UNDER_REVIEW"&&reviewPermission.canApprove&&<button className={styles.primary} onClick={()=>void perform(()=>salnAdminApi.compliant(detail.id,"Complete and in proper form."),"SALN marked compliant.")}>Mark compliant</button>}{detail.status==="COMPLIANT"&&reviewPermission.canFinalize&&<button className={styles.primary} onClick={()=>void perform(()=>salnAdminApi.lock(detail.id,"Finalized by HR/RCC."),"SALN locked.")}>Lock final SALN</button>}{detail.status!=="VOIDED"&&reviewPermission.canDelete&&<button className={styles.danger} onClick={async()=>{const result=await Swal.fire({title:"Void SALN?",input:"textarea",inputLabel:"Required reason",showCancelButton:true,inputValidator:value=>value?undefined:"Reason is required"});if(result.isConfirmed)void perform(()=>salnAdminApi.voidRecord(detail.id,result.value as string),"SALN voided with an audit record.");}}>Void record</button>}</div>
   {detail.status==="UNDER_REVIEW"&&reviewPermission.canEdit&&<div className={styles.actionForm}><h3>Return for correction</h3><input placeholder="Section" value={correction.section} onChange={e=>setCorrection({...correction,section:e.target.value})}/><input placeholder="Field (optional)" value={correction.field} onChange={e=>setCorrection({...correction,field:e.target.value})}/><textarea placeholder="Required correction" value={correction.message} onChange={e=>setCorrection({...correction,message:e.target.value})}/><button disabled={!correction.message.trim()} onClick={()=>void perform(()=>salnAdminApi.correct(detail.id,correction.section,correction.field,correction.message),"SALN returned to the employee for correction.")}>Return for correction</button></div>}
   {(detail.status==="COMPLIANT"||detail.status==="LOCKED")&&reviewPermission.canFinalize&&!detail.repositorySubmittedAt&&<div className={styles.actionForm}><h3>Repository submission</h3><input placeholder="Repository agency" value={repository.repositoryAgency} onChange={e=>setRepository({...repository,repositoryAgency:e.target.value})}/><input type="datetime-local" value={repository.submittedAt} onChange={e=>setRepository({...repository,submittedAt:e.target.value})}/><input placeholder="Reference number" value={repository.referenceNo} onChange={e=>setRepository({...repository,referenceNo:e.target.value})}/><textarea placeholder="Remarks" value={repository.remarks} onChange={e=>setRepository({...repository,remarks:e.target.value})}/><button disabled={!repository.repositoryAgency||!repository.submittedAt||!repository.referenceNo} onClick={()=>void perform(()=>salnAdminApi.repository(detail.id,{...repository,submittedAt:`${repository.submittedAt}:00`}),"Repository submission recorded; the SALN is locked.")}>Record submission</button></div>}
   {auditPermission.canAccess&&<div className={styles.audit}><h3>Audit trail</h3>{audits.map(item=><p key={item.id}><strong>{item.action.replaceAll("_"," ")}</strong> by {item.performedBy} on {new Date(item.performedAt).toLocaleString()} {item.remarks?`— ${item.remarks}`:""}</p>)}</div>}
  </section>}
   {requirementPermission.canAccess&&<section className={styles.requirements}>
    <h2>Filing requirements</h2>
    <p className={styles.requirementNote}>Use bulk generation for the annual agency-wide obligation, or create one requirement at a time for individual, assumption, separation, or exceptional cases.</p>
    {requirementPermission.canAdd&&<>
     <div className={styles.bulkRequirement}><div><strong>Bulk annual generation</strong><span>Includes employees appointed by December 31 with no separation effective by that date. Existing requirements are skipped safely.</span></div><label>Year<input aria-label="Annual SALN year" type="number" min="1900" max="2200" value={bulkYear} onChange={e=>setBulkYear(Number(e.target.value))}/></label><button type="button" disabled={busy} onClick={()=>void generateAnnualRequirements()}>{busy?"Please wait…":"Generate annual requirements"}</button></div>
     <div className={styles.requirementDivider}><span>or create individually</span></div>
     <div className={styles.requirementForm}><select aria-label="Employee" required value={requirement.employeeId} onChange={e=>setRequirement({...requirement,employeeId:e.target.value})}><option value="">Select employee</option>{employees.map(employee=><option key={employee.employeeId} value={employee.employeeId}>{employee.fullName||[employee.firstname,employee.lastname,employee.suffix].filter(Boolean).join(" ")} {employee.employeeNo?`(${employee.employeeNo})`:""}</option>)}</select><select aria-label="Filing type" value={requirement.filingType} onChange={e=>{const type=e.target.value as FilingType;setRequirement({...requirement,filingType:type,referenceDate:type==="ANNUAL"?`${new Date().getFullYear()}-12-31`:requirement.referenceDate});}}><option>ANNUAL</option><option>ASSUMPTION</option><option>SEPARATION</option></select><input aria-label="Reference date" required type="date" value={requirement.referenceDate} onChange={e=>setRequirement({...requirement,referenceDate:e.target.value})}/><button type="button" disabled={busy} onClick={()=>void createRequirement()}>{busy?"Please wait…":"Create requirement"}</button></div>
    </>}
    <div className={styles.requirementToolbar}><label>Status<select value={requirementStatus} onChange={e=>{setRequirementStatus(e.target.value);setRequirementPage(1);}}><option value="ALL">All statuses</option><option value="NOT_FILED">Not filed</option><option value="DRAFT">Draft</option><option value="FILED">Filed</option><option value="OVERDUE">Overdue</option><option value="WAIVED">Waived</option></select></label><span>{filteredRequirements.length} requirement{filteredRequirements.length===1?"":"s"}</span></div>
    <div className={styles.requirementGrid}>{visibleRequirements.map(item=><article key={item.id}><strong>{item.employeeNo} — {item.filingType} {item.salnYear}</strong><span>{item.status.replaceAll("_"," ")}</span><small>Due {item.dueDate}</small></article>)}</div>
    {filteredRequirements.length===0&&<p className={styles.emptyState}>No filing requirements match this status.</p>}
    {requirementPageCount>1&&<nav className={styles.pagination} aria-label="Filing requirements pagination"><button type="button" disabled={safeRequirementPage===1} onClick={()=>setRequirementPage(Math.max(1,safeRequirementPage-1))}>Previous</button><span>Page {safeRequirementPage} of {requirementPageCount}</span><button type="button" disabled={safeRequirementPage===requirementPageCount} onClick={()=>setRequirementPage(Math.min(requirementPageCount,safeRequirementPage+1))}>Next</button></nav>}
   </section>}
    </div>
   </div>
  </div>
 </div>;
}
