"use client";

import { useCallback, useEffect, useState } from "react";
import Swal from "sweetalert2";
import { localStorageUtil, type FeaturePermission } from "@/lib/utils/localStorageUtil";
import { runtimeConfig } from "@/lib/utils/runtimeConfig";
import { onboardingJson, OnboardingApiError, type AppointmentIntake, type AppointmentResult } from "@/lib/services/onboarding";
import styles from "@/styles/Onboarding.module.scss";

const denied: FeaturePermission = { canAccess: false, canAdd: false, canEdit: false, canDelete: false, canPublish: false,
  canSubmit: false, canApprove: false, canFinalize: false, dataScope: "NONE" };
const failure = (error: unknown) => error instanceof OnboardingApiError && error.status === 409
  ? `This intake or an authoritative source changed. Reload before retrying. ${error.message}`
  : error instanceof Error ? error.message : "Unable to complete the request.";

export default function AppointmentIntakeWorkspace() {
  const [intakePermission, setIntakePermission] = useState(denied); const [onboardingPermission, setOnboardingPermission] = useState(denied);
  const [ready, setReady] = useState(false); const [items, setItems] = useState<AppointmentIntake[]>([]);
  const [selected, setSelected] = useState<AppointmentIntake | null>(null); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const [identity, setIdentity] = useState({ decision: "LINK_EXISTING_EMPLOYEE", employeeId: "", employeeNo: "", biometricNo: "", role: "2" });
  const [evidence, setEvidence] = useState<Record<string, { evidenceReference: string; evidenceFingerprint: string }>>({});
  const [appointment, setAppointment] = useState({ natureOfAppointmentId: "", appointmentIssuedDate: "", assumptionToDutyDate: "", details: "" });
  const [result, setResult] = useState<AppointmentResult | null>(null);
  const load = useCallback(async () => { try { const values = await onboardingJson<AppointmentIntake[]>("/api/hrm/v1/appointment-intakes"); setItems(values); setNotice(""); }
    catch (error) { setNotice(failure(error)); } }, []);
  const open = useCallback(async (id: string) => { try { const value = await onboardingJson<AppointmentIntake>(`/api/hrm/v1/appointment-intakes/${id}`); setSelected(value);
    setIdentity({ decision: value.identityDecision ?? "LINK_EXISTING_EMPLOYEE", employeeId: value.employeeId?.toString() ?? "", employeeNo: value.employeeNo ?? "", biometricNo: "", role: "2" }); setNotice(""); }
    catch (error) { setNotice(failure(error)); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => { const intake = localStorageUtil.getFeaturePermission("hrm.appointment-intake");
    const onboarding = localStorageUtil.getFeaturePermission("hrm.onboarding"); setIntakePermission(intake); setOnboardingPermission(onboarding); setReady(true); if (intake.canAccess) void load(); }, 0); return () => clearTimeout(timer); }, [load]);
  async function act<T>(path: string, method: "POST" | "PUT", body: object, success: string): Promise<T | null> { setBusy(true); try { const value = await onboardingJson<T>(path, { method, body: JSON.stringify(body) }); setNotice(success); await load(); return value; }
    catch (error) { await Swal.fire("Appointment intake action failed", failure(error), "error"); return null; } finally { setBusy(false); } }
  async function caseAction(action: "begin-review" | "approve" | "complete-onboarding") { if (!selected) return; const value = await act<AppointmentIntake>(`/api/hrm/v1/appointment-intakes/${selected.id}/${action}`, "POST", { recordVersion: selected.recordVersion }, `${action.replaceAll("-", " ")} recorded.`); if (value) setSelected(value); }
  async function returnCase() { if (!selected) return; const answer = await Swal.fire({ title: "Return intake", input: "textarea", inputLabel: "Required reason", showCancelButton: true, inputValidator: value => value.trim() ? undefined : "A reason is required." });
    if (!answer.isConfirmed) return; const value = await act<AppointmentIntake>(`/api/hrm/v1/appointment-intakes/${selected.id}/return`, "POST", { reason: answer.value, recordVersion: selected.recordVersion }, "Intake returned with an auditable reason."); if (value) setSelected(value); }
  async function saveIdentity() { if (!selected) return; const value = await act<AppointmentIntake>(`/api/hrm/v1/appointment-intakes/${selected.id}/identity-resolution`, "PUT", {
    decision: identity.decision, employeeId: identity.decision === "LINK_EXISTING_EMPLOYEE" ? Number(identity.employeeId) : null,
    employeeNo: identity.employeeNo || null, biometricNo: identity.biometricNo || null, role: identity.role || null, recordVersion: selected.recordVersion }, "Identity resolution saved without creating an employee."); if (value) setSelected(value); }
  async function checklist(itemId: string, status: "SUBMITTED" | "VERIFIED" | "REJECTED") { if (!selected) return; const input = evidence[itemId] ?? { evidenceReference: "", evidenceFingerprint: "" };
    const value = await act<AppointmentIntake>(`/api/hrm/v1/appointment-intakes/${selected.id}/checklist/${itemId}`, "PUT", { status,
      evidenceReference: status === "SUBMITTED" ? input.evidenceReference : null, evidenceFingerprint: status === "SUBMITTED" ? input.evidenceFingerprint : null,
      recordVersion: selected.recordVersion }, `Checklist item ${status.toLowerCase()} with audit attribution.`); if (value) setSelected(value); }
  async function createAppointment() { if (!selected) return; const value = await act<AppointmentResult>(`/api/hrm/v1/appointment-intakes/${selected.id}/create-appointment`, "POST", {
    natureOfAppointmentId: Number(appointment.natureOfAppointmentId), appointmentIssuedDate: new Date(appointment.appointmentIssuedDate).toISOString().slice(0, 19),
    assumptionToDutyDate: new Date(appointment.assumptionToDutyDate).toISOString().slice(0, 19), details: appointment.details, recordVersion: selected.recordVersion }, "Employee and appointment were created atomically from authoritative sources.");
    if (value) { setResult(value); await open(selected.id); } }
  function activationUrl(token: string): string { return `${runtimeConfig.getUiUrl("employee-portal").replace(/\/$/, "")}/employee-portal/activate?token=${encodeURIComponent(token)}`; }

  if (!ready) return <div className={styles.notice}>Checking Administrative permissions…</div>;
  if (!intakePermission.canAccess) return <section className={styles.card}><h1>Access denied</h1><p>Your Administrative ruleset does not grant appointment intake access.</p></section>;
  return <div className={styles.page} data-testid="phase5e-appointment-intake"><section className={styles.card}><h1>Appointment intake and onboarding</h1><p>This workspace keeps identity review, evidence verification, appointment creation, and activation auditable. Appointment creation revalidates Administrative Plantilla, position, business unit, nature, salary, and fingerprint sources atomically.</p>{notice && <div className={styles.notice}>{notice}</div>}</section>
    <section className={styles.card}><h2>Intake inbox</h2>{items.length === 0 ? <p>No acknowledged appointment handoffs are waiting.</p> : <table className={styles.table}><thead><tr><th>Applicant / application</th><th>Status</th><th>Employee</th><th>Action</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td>{item.applicantId}<br /><small>{item.applicationId}</small></td><td>{item.status}</td><td>{item.employeeNo ?? "Not resolved"}</td><td><button onClick={() => void open(item.id)}>Open</button></td></tr>)}</tbody></table>}</section>
    {selected && <><section className={styles.card}><h2>Identity resolution</h2><p>Handoff {selected.handoffId} · Version {selected.recordVersion}</p><div className={styles.grid}>
      <div className={styles.field}><label htmlFor="identityDecision">Decision</label><select id="identityDecision" value={identity.decision} onChange={e => setIdentity({ ...identity, decision: e.target.value })}><option value="LINK_EXISTING_EMPLOYEE">Link existing employee</option><option value="CREATE_NEW_EMPLOYEE">Create employee only with appointment</option></select></div>
      {identity.decision === "LINK_EXISTING_EMPLOYEE" ? <div className={styles.field}><label htmlFor="employeeId">Existing employee ID</label><input id="employeeId" value={identity.employeeId} onChange={e => setIdentity({ ...identity, employeeId: e.target.value })} /></div> : <><div className={styles.field}><label htmlFor="employeeNo">Employee no.</label><input id="employeeNo" value={identity.employeeNo} onChange={e => setIdentity({ ...identity, employeeNo: e.target.value })} /></div><div className={styles.field}><label htmlFor="biometricNo">Biometric no.</label><input id="biometricNo" value={identity.biometricNo} onChange={e => setIdentity({ ...identity, biometricNo: e.target.value })} /></div><div className={styles.field}><label htmlFor="role">Initial non-administrator role</label><input id="role" value={identity.role} onChange={e => setIdentity({ ...identity, role: e.target.value })} /></div></>}
      </div><div className={styles.actions}>{onboardingPermission.canEdit && <button disabled={busy} onClick={() => void caseAction("begin-review")}>Begin review</button>}{onboardingPermission.canEdit && <button disabled={busy} onClick={() => void saveIdentity()}>Save identity decision</button>}{onboardingPermission.canEdit && <button disabled={busy} onClick={() => void returnCase()}>Return</button>}</div></section>
      <section className={styles.card}><h2>Onboarding checklist</h2>{selected.items.length === 0 ? <p>No checklist items.</p> : <table className={styles.table}><thead><tr><th>Requirement</th><th>Status / attribution</th><th>Evidence reference and SHA-256</th><th>Action</th></tr></thead><tbody>{selected.items.map(item => { const input = evidence[item.id] ?? { evidenceReference: "", evidenceFingerprint: "" }; return <tr key={item.id}><td>{item.label}{item.required && " *"}</td><td>{item.status}<br /><small>Submitted: {item.completedBy ?? "—"}<br />Verified: {item.verifiedBy ?? "—"}</small></td><td>{onboardingPermission.canEdit && <><input aria-label={`${item.label} evidence reference`} placeholder="Secure vault reference" value={input.evidenceReference} onChange={e => setEvidence({ ...evidence, [item.id]: { ...input, evidenceReference: e.target.value } })} /><input aria-label={`${item.label} evidence fingerprint`} placeholder="64-character SHA-256" value={input.evidenceFingerprint} onChange={e => setEvidence({ ...evidence, [item.id]: { ...input, evidenceFingerprint: e.target.value } })} /></>}</td><td><div className={styles.actions}>{onboardingPermission.canEdit && <button disabled={busy || (item.evidenceRequired && (!input.evidenceReference || input.evidenceFingerprint.length !== 64))} onClick={() => void checklist(item.id, "SUBMITTED")}>Submit</button>}{onboardingPermission.canEdit && <button disabled={busy || item.status !== "SUBMITTED"} onClick={() => void checklist(item.id, "VERIFIED")}>Verify independently</button>}{onboardingPermission.canEdit && <button disabled={busy} onClick={() => void checklist(item.id, "REJECTED")}>Reject</button>}</div></td></tr>; })}</tbody></table>}
      <div className={styles.actions}>{onboardingPermission.canApprove && <button disabled={busy} onClick={() => void caseAction("approve")}>Approve for appointment</button>}</div></section>
      <section className={styles.card}><h2>Authoritative appointment preview and atomic creation</h2><p>The server resolves and rechecks the selected Plantilla, job position, business unit, salary schedule, qualification standard, and nature of appointment at submission. No employee is created before this operation commits.</p><div className={styles.grid}>
        <div className={styles.field}><label htmlFor="nature">Nature of appointment ID</label><input id="nature" value={appointment.natureOfAppointmentId} onChange={e => setAppointment({ ...appointment, natureOfAppointmentId: e.target.value })} /></div>
        <div className={styles.field}><label htmlFor="issued">Appointment issued</label><input id="issued" type="datetime-local" value={appointment.appointmentIssuedDate} onChange={e => setAppointment({ ...appointment, appointmentIssuedDate: e.target.value })} /></div>
        <div className={styles.field}><label htmlFor="assumption">Assumption to duty</label><input id="assumption" type="datetime-local" value={appointment.assumptionToDutyDate} onChange={e => setAppointment({ ...appointment, assumptionToDutyDate: e.target.value })} /></div>
        <div className={styles.field}><label htmlFor="details">Appointment details</label><textarea id="details" value={appointment.details} onChange={e => setAppointment({ ...appointment, details: e.target.value })} /></div></div>
        <div className={styles.actions}>{intakePermission.canFinalize && <button disabled={busy || !appointment.natureOfAppointmentId || !appointment.appointmentIssuedDate || !appointment.assumptionToDutyDate || !appointment.details} onClick={() => void createAppointment()}>Create employee and appointment atomically</button>}{onboardingPermission.canFinalize && <button disabled={busy} onClick={() => void caseAction("complete-onboarding")}>Complete onboarding</button>}</div>
        {result && <div className={styles.success}><strong>Appointment {result.appointmentId} created for employee {result.employeeId}.</strong>{result.activationToken ? <><p>This one-time activation link is shown only in this response. Transfer it through the approved secure channel before {result.activationExpiresAt ? new Date(result.activationExpiresAt).toLocaleString() : "expiry"}.</p><input readOnly aria-label="One-time employee activation link" value={activationUrl(result.activationToken)} /></> : <p>No new activation link was issued. A retry safely returned the existing employee and appointment.</p>}</div>}
      </section></>}
  </div>;
}
